### ISSUE TITLE
add operator() for defered message replying

### ISSUE THREAD

**Issue by majestrate** [loki-project/loki-mq#47]
add something like:

```
auto reply = msg.defer_reply(reply_type::whatever);
reply(some_Junk_or_stuff);
```

**Comment by jagerman** [comment]
I think we could actually just add the `operator()` to DeferredSend without needing a new method/subclass/etc.: if `reply_tag` is set then the incoming message was a reply and it can forward arguments to `reply()`; otherwise it was a 1-way message and `operator()` can forward to `back()`.  (And if you need to defer a full request, or something else exotic you can still use the named methods).
